name: Build Succeeds on PR

on: 
  pull_request: 
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: cache 
        uses: actions/cache@v4
        with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*. tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install

      - name: Generate prisma client
        run: npm run db:generate

      - name: Run Build 
        run: npm run build